/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            service: string;
                            /** Format: date-time */
                            timestamp: string;
                            request_id: string;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe by id */
        get: {
            parameters: {
                query?: {
                    /** @description Response projection for ingredient and inline measurement units. */
                    units?: "source" | "metric" | "imperial";
                    /** @description Optional ingredient grouping strategy for response rendering. */
                    group_by?: "flat" | "category" | "component";
                    /** @description Whether to append inline measurements directly inside step instructions. */
                    inline_measurements?: boolean;
                };
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recipe version history with causal chat/thread context */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeHistoryResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/cookbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saved cookbook recipes grouped with category precedence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cookbook response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["RecipeCard"][];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a recipe to cookbook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Save status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            saved: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        /** Unsave a recipe */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Save status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            saved: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create and attach a child recipe (side/appetizer/etc) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttachmentRequest"];
                };
            };
            responses: {
                /** @description Parent recipe with updated attachments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe: components["schemas"]["Recipe"];
                            /** Format: uuid */
                            attachment_id: string;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove attachment link */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                    attachment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Parent recipe with updated attachments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe: components["schemas"]["Recipe"];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        /** Update attachment position or relation type */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                    attachment_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAttachmentRequest"];
                };
            };
            responses: {
                /** @description Parent recipe with updated attachments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe: components["schemas"]["Recipe"];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user collections */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Collection"][];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        /** Create collection */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Created collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Collection"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add recipe to collection */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        recipe_id: string;
                    };
                };
            };
            responses: {
                /** @description Item add status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user preferences */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Preferences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreferenceProfile"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user preferences */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PreferenceProfile"];
                };
            };
            responses: {
                /** @description Updated preferences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreferenceProfile"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        trace?: never;
    };
    "/onboarding/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get onboarding completion state for authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Onboarding state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingState"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue onboarding interview and persist preference updates */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardingChatRequest"];
                };
            };
            responses: {
                /** @description Onboarding assistant response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingChatResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active user memories and snapshot */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memory response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryListResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft-delete a specific memory */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        memory_id: string;
                    };
                };
            };
            responses: {
                /** @description Forget status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset all user memories */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reset status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User-scoped changelog timeline */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Changelog response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangelogResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image-jobs/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process pending image jobs for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Processing summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            processed: number;
                            ready: number;
                            failed: number;
                            pending: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata-jobs/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process due recipe metadata jobs (internal authenticated scope) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Metadata queue processing summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetadataJobsProcessResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata-jobs/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-queue a metadata job safely (internal authenticated scope) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        job_id: string;
                    };
                };
            };
            responses: {
                /** @description Retry status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            job: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                status: "pending" | "processing" | "ready" | "failed";
                                attempts: number;
                                /** Format: date-time */
                                next_attempt_at: string;
                            };
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory-jobs/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process due memory extraction jobs (internal authenticated scope) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Memory queue processing summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryJobsProcessResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory-jobs/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-queue a memory job safely (internal authenticated scope) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        job_id: string;
                    };
                };
            };
            responses: {
                /** @description Retry status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            job: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                status: "pending" | "processing" | "ready" | "failed";
                                attempts: number;
                                /** Format: date-time */
                                next_attempt_at: string;
                            };
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new chat session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            responses: {
                /** @description Chat session created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chat session thread */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chat session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a message to chat session thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            responses: {
                /** @description Updated chat session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{id}/candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mutate ephemeral candidate recipe set state for a chat session */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchCandidateRequest"];
                };
            };
            responses: {
                /** @description Updated chat session candidate set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PatchCandidateResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        trace?: never;
    };
    "/chat/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist all remaining candidate components to cookbook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CommitChatRecipesRequest"];
                };
            };
            responses: {
                /** @description Candidate components committed and linked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommitChatRecipesResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/categories/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a user category override */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category: string;
                    };
                };
            };
            responses: {
                /** @description Override status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/categories/override/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove category override */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                    category: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Remove status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch graph entities and edges related to a recipe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entities: components["schemas"]["GraphEntity"][];
                            edges: components["schemas"]["GraphEdge"][];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            code: string;
            message: string;
            details?: unknown;
            request_id: string;
        };
        Ingredient: {
            name: string;
            amount: number;
            unit: string;
            preparation?: string;
            category?: string;
            /** Format: uuid */
            ingredient_id?: string | null;
            /** @enum {string} */
            normalized_status?: "normalized" | "needs_retry";
            component?: string | null;
        };
        IngredientGroup: {
            key: string;
            label: string;
            ingredients: components["schemas"]["Ingredient"][];
        };
        InlineMeasurement: {
            ingredient: string;
            amount: number;
            unit: string;
        };
        Step: {
            index: number;
            instruction: string;
            timer_seconds?: number;
            notes?: string;
            inline_measurements?: components["schemas"]["InlineMeasurement"][];
        };
        Nutrition: {
            calories?: number;
            protein_g?: number;
            carbs_g?: number;
            fat_g?: number;
            fiber_g?: number;
            sugar_g?: number;
            sodium_mg?: number;
        };
        RecipeMetadata: {
            vibe?: string;
            flavor_profile?: string[];
            nutrition?: components["schemas"]["Nutrition"];
            difficulty?: string;
            allergens?: string[];
            substitutions?: {
                from?: string;
                to?: string;
                note?: string;
            }[];
            timing?: {
                prep_minutes?: number;
                cook_minutes?: number;
                total_minutes?: number;
            };
            cuisine_tags?: string[];
            occasion_tags?: string[];
            pairing_rationale?: string[];
            serving_notes?: string[];
            additionalProperties?: {
                [key: string]: unknown;
            };
        };
        RecipePayloadAttachment: {
            title: string;
            relation_type: string;
            recipe: {
                [key: string]: unknown;
            };
        };
        RecipePayload: {
            title: string;
            description?: string;
            servings: number;
            ingredients: components["schemas"]["Ingredient"][];
            steps: components["schemas"]["Step"][];
            notes?: string;
            pairings?: string[];
            emoji?: string[];
            metadata?: components["schemas"]["RecipeMetadata"];
            attachments?: components["schemas"]["RecipePayloadAttachment"][];
        };
        RecipeAttachment: {
            /** Format: uuid */
            attachment_id: string;
            relation_type: string;
            position: number;
            recipe: components["schemas"]["Recipe"];
        };
        Recipe: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            summary?: string;
            /** Format: uri */
            image_url?: string | null;
            /** @enum {string} */
            image_status?: "pending" | "ready" | "failed";
            servings: number;
            ingredients: components["schemas"]["Ingredient"][];
            ingredient_groups?: components["schemas"]["IngredientGroup"][];
            steps: components["schemas"]["Step"][];
            notes?: string;
            pairings?: string[];
            emoji?: string[];
            metadata?: components["schemas"]["RecipeMetadata"];
            attachments?: components["schemas"]["RecipeAttachment"][];
            /** @enum {string} */
            visibility: "public" | "private";
            /** Format: date-time */
            updated_at: string;
            version?: components["schemas"]["RecipeVersion"];
        };
        RecipeCard: {
            /** Format: uuid */
            id: string;
            title: string;
            summary: string;
            /** Format: uri */
            image_url?: string | null;
            /** @enum {string} */
            image_status?: "pending" | "ready" | "failed";
            category?: string;
            /** Format: date-time */
            updated_at: string;
        };
        RecipeVersion: {
            /** Format: uuid */
            version_id: string;
            /** Format: uuid */
            recipe_id: string;
            /** Format: uuid */
            parent_version_id?: string | null;
            diff_summary?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RecipeHistoryResponse: {
            /** Format: uuid */
            recipe_id: string;
            /** Format: uuid */
            source_chat_id?: string | null;
            versions: {
                /** Format: uuid */
                id?: string;
                /** Format: uuid */
                parent_version_id?: string | null;
                diff_summary?: string | null;
                /** Format: date-time */
                created_at?: string;
                payload?: {
                    [key: string]: unknown;
                };
                /** Format: uuid */
                created_by?: string | null;
            }[];
            version_events?: {
                [key: string]: unknown;
            }[];
            chat_messages: components["schemas"]["ChatMessage"][];
        };
        Memory: {
            /** Format: uuid */
            id: string;
            memory_type: string;
            memory_kind: string;
            memory_content?: {
                [key: string]: unknown;
            };
            confidence: number;
            salience: number;
            status: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MemoryListResponse: {
            items: components["schemas"]["Memory"][];
            snapshot: {
                [key: string]: unknown;
            };
        };
        ChangelogEvent: {
            /** Format: uuid */
            id: string;
            scope: string;
            entity_type: string;
            entity_id?: string | null;
            action: string;
            request_id?: string;
            before_json?: {
                [key: string]: unknown;
            } | null;
            after_json?: {
                [key: string]: unknown;
            } | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ChangelogResponse: {
            items: components["schemas"]["ChangelogEvent"][];
        };
        MetadataJobsProcessResponse: {
            reaped: number;
            claimed: number;
            processed: number;
            ready: number;
            failed: number;
            pending: number;
            queue: {
                pending: number;
                processing: number;
                ready: number;
                failed: number;
            };
        };
        PreferenceProfile: {
            free_form?: string;
            dietary_preferences: string[];
            dietary_restrictions?: string[];
            skill_level: string;
            equipment: string[];
            cuisines?: string[];
            aversions?: string[];
            cooking_for?: string;
            max_difficulty?: number;
            presentation_preferences?: {
                [key: string]: unknown;
            };
        };
        AssistantReply: {
            text: string;
            tone?: string;
            emoji?: string[];
            suggested_next_actions?: string[];
            focus_summary?: string;
        };
        OnboardingState: {
            completed: boolean;
            progress: number;
            missing_topics: string[];
            state: {
                [key: string]: unknown;
            };
        };
        OnboardingChatMessage: {
            /** @enum {string} */
            role: "assistant" | "user";
            content: string;
            /** Format: date-time */
            created_at?: string;
        };
        OnboardingChatRequest: {
            message?: string;
            transcript?: components["schemas"]["OnboardingChatMessage"][];
            state?: {
                [key: string]: unknown;
            };
        };
        OnboardingChatResponse: {
            assistant_reply: components["schemas"]["AssistantReply"];
            onboarding_state: components["schemas"]["OnboardingState"];
            preference_updates?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        ChatLoopState: "ideation" | "candidate_presented" | "iterating";
        CandidateRecipeComponent: {
            component_id: string;
            /** @enum {string} */
            role: "main" | "side" | "appetizer" | "dessert" | "drink";
            title: string;
            recipe: components["schemas"]["RecipePayload"];
        };
        CandidateRecipeSet: {
            candidate_id: string;
            revision: number;
            active_component_id: string;
            components: components["schemas"]["CandidateRecipeComponent"][];
        };
        PatchCandidateRequest: {
            /** @enum {string} */
            action: "set_active_component" | "delete_component" | "clear_candidate";
            component_id?: string;
        };
        PatchCandidateResponse: components["schemas"]["ChatSession"];
        CommitChatRecipesRequest: Record<string, never>;
        CommitChatRecipesResponse: components["schemas"]["ChatSession"] & {
            commit: {
                candidate_id: string;
                revision: number;
                committed_count: number;
                recipes: {
                    component_id: string;
                    /** @enum {string} */
                    role: "main" | "side" | "appetizer" | "dessert" | "drink";
                    title: string;
                    /** Format: uuid */
                    recipe_id: string;
                    /** Format: uuid */
                    recipe_version_id: string;
                }[];
                links: {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    parent_recipe_id: string;
                    /** Format: uuid */
                    child_recipe_id: string;
                    relation_type: string;
                    position: number;
                }[];
                post_save_options: ("continue_chat" | "restart_chat" | "go_to_cookbook")[];
            };
        };
        MemoryJobsProcessResponse: {
            processed: number;
            succeeded: number;
            failed: number;
            queue: {
                pending: number;
                processing: number;
                ready: number;
                failed: number;
            };
        };
        CreateAttachmentRequest: {
            relation_type: string;
            position?: number;
            prompt?: string;
            recipe?: {
                [key: string]: unknown;
            };
        };
        UpdateAttachmentRequest: {
            relation_type?: string;
            position?: number;
        };
        ChatMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ChatSession: {
            /** Format: uuid */
            id: string;
            messages: components["schemas"]["ChatMessage"][];
            loop_state: components["schemas"]["ChatLoopState"];
            assistant_reply: components["schemas"]["AssistantReply"] | null;
            candidate_recipe_set?: components["schemas"]["CandidateRecipeSet"] | null;
            memory_context_ids: string[];
            context_version: number;
            ui_hints?: {
                show_generation_animation?: boolean;
                focus_component_id?: string;
            };
            context?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Collection: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        GraphEntity: {
            /** Format: uuid */
            id: string;
            entity_type: string;
            label: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        GraphEdge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            from_entity_id: string;
            /** Format: uuid */
            to_entity_id: string;
            relation_type: string;
            confidence: number;
            source?: string;
        };
    };
    responses: {
        /** @description Error envelope */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        RecipeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
