/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recipes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a recipe from user intent and memory-aware context */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateRecipeRequest"];
                };
            };
            responses: {
                /** @description Generated recipe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateRecipeResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/tweak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tweak an existing recipe and create a new version */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TweakRecipeRequest"];
                };
            };
            responses: {
                /** @description Tweaked recipe version */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TweakRecipeResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recipe version history with causal draft/thread context */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeHistoryResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/cookbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saved cookbook recipes grouped with category precedence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cookbook response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["RecipeCard"][];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a recipe to cookbook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Save status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            saved: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        /** Unsave a recipe */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Save status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            saved: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create and attach a child recipe (side/appetizer/etc) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttachmentRequest"];
                };
            };
            responses: {
                /** @description Parent recipe with updated attachments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe: components["schemas"]["Recipe"];
                            /** Format: uuid */
                            attachment_id: string;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove attachment link */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                    attachment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Parent recipe with updated attachments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe: components["schemas"]["Recipe"];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        /** Update attachment position or relation type */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                    attachment_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAttachmentRequest"];
                };
            };
            responses: {
                /** @description Parent recipe with updated attachments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe: components["schemas"]["Recipe"];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user collections */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Collection"][];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        /** Create collection */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Created collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Collection"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add recipe to collection */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        recipe_id: string;
                    };
                };
            };
            responses: {
                /** @description Item add status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user preferences */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Preferences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreferenceProfile"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user preferences */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PreferenceProfile"];
                };
            };
            responses: {
                /** @description Updated preferences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreferenceProfile"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        trace?: never;
    };
    "/onboarding/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get onboarding completion state for authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Onboarding state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingState"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue onboarding interview and persist preference updates */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardingChatRequest"];
                };
            };
            responses: {
                /** @description Onboarding assistant response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingChatResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active user memories and snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memory response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryListResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft-delete a specific memory */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        memory_id: string;
                    };
                };
            };
            responses: {
                /** @description Forget status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset all user memories */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reset status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User-scoped changelog timeline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Changelog response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangelogResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image-jobs/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process pending image jobs for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Processing summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            processed: number;
                            ready: number;
                            failed: number;
                            pending: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipe-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new recipe draft chat session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            responses: {
                /** @description Draft created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeDraft"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipe-drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recipe draft thread */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Draft */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeDraft"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipe-drafts/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a message to recipe draft thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            responses: {
                /** @description Updated draft */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeDraft"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipe-drafts/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize draft into persisted recipe + version */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Finalized recipe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeFinalizeResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/categories/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a user category override */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category: string;
                    };
                };
            };
            responses: {
                /** @description Override status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/categories/override/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove category override */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                    category: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Remove status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch graph entities and edges related to a recipe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RecipeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entities: components["schemas"]["GraphEntity"][];
                            edges: components["schemas"]["GraphEdge"][];
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            code: string;
            message: string;
            details?: unknown;
            request_id: string;
        };
        Ingredient: {
            name: string;
            amount: number;
            unit: string;
            preparation?: string;
            category?: string;
        };
        InlineMeasurement: {
            ingredient: string;
            amount: number;
            unit: string;
        };
        Step: {
            index: number;
            instruction: string;
            timer_seconds?: number;
            notes?: string;
            inline_measurements?: components["schemas"]["InlineMeasurement"][];
        };
        Nutrition: {
            calories?: number;
            protein_g?: number;
            carbs_g?: number;
            fat_g?: number;
            fiber_g?: number;
            sugar_g?: number;
            sodium_mg?: number;
        };
        RecipeMetadata: {
            vibe?: string;
            flavor_profile?: string[];
            nutrition?: components["schemas"]["Nutrition"];
            difficulty?: string;
            allergens?: string[];
            substitutions?: {
                from?: string;
                to?: string;
                note?: string;
            }[];
            timing?: {
                prep_minutes?: number;
                cook_minutes?: number;
                total_minutes?: number;
            };
            cuisine_tags?: string[];
            occasion_tags?: string[];
            pairing_rationale?: string[];
            serving_notes?: string[];
            additionalProperties?: {
                [key: string]: unknown;
            };
        };
        RecipeAttachment: {
            /** Format: uuid */
            attachment_id: string;
            relation_type: string;
            position: number;
            recipe: components["schemas"]["Recipe"];
        };
        Recipe: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            summary?: string;
            /** Format: uri */
            image_url?: string;
            /** @enum {string} */
            image_status?: "pending" | "ready" | "failed";
            servings: number;
            ingredients: components["schemas"]["Ingredient"][];
            steps: components["schemas"]["Step"][];
            notes?: string;
            pairings?: string[];
            emoji?: string[];
            metadata?: components["schemas"]["RecipeMetadata"];
            attachments?: components["schemas"]["RecipeAttachment"][];
            /** @enum {string} */
            visibility: "public" | "private";
            /** Format: date-time */
            updated_at: string;
            version?: components["schemas"]["RecipeVersion"];
        };
        RecipeCard: {
            /** Format: uuid */
            id: string;
            title: string;
            summary: string;
            /** Format: uri */
            image_url?: string;
            /** @enum {string} */
            image_status?: "pending" | "ready" | "failed";
            category?: string;
            /** Format: date-time */
            updated_at: string;
        };
        RecipeVersion: {
            /** Format: uuid */
            version_id: string;
            /** Format: uuid */
            recipe_id: string;
            /** Format: uuid */
            parent_version_id?: string;
            diff_summary?: string;
            /** Format: date-time */
            created_at: string;
        };
        RecipeHistoryResponse: {
            /** Format: uuid */
            recipe_id: string;
            /** Format: uuid */
            source_draft_id?: string;
            versions: {
                /** Format: uuid */
                id?: string;
                /** Format: uuid */
                parent_version_id?: string;
                diff_summary?: string;
                /** Format: date-time */
                created_at?: string;
            }[];
            version_events?: {
                [key: string]: unknown;
            }[];
            draft_messages: components["schemas"]["RecipeDraftMessage"][];
        };
        Memory: {
            /** Format: uuid */
            id: string;
            memory_type: string;
            memory_kind: string;
            memory_content?: {
                [key: string]: unknown;
            };
            confidence: number;
            salience: number;
            status: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MemoryListResponse: {
            items: components["schemas"]["Memory"][];
            snapshot: {
                [key: string]: unknown;
            };
        };
        ChangelogEvent: {
            /** Format: uuid */
            id: string;
            scope: string;
            entity_type: string;
            entity_id?: string;
            action: string;
            request_id?: string;
            before_json?: {
                [key: string]: unknown;
            };
            after_json?: {
                [key: string]: unknown;
            };
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ChangelogResponse: {
            items: components["schemas"]["ChangelogEvent"][];
        };
        PreferenceProfile: {
            free_form?: string;
            dietary_preferences: string[];
            dietary_restrictions?: string[];
            skill_level: string;
            equipment: string[];
            cuisines?: string[];
            aversions?: string[];
            cooking_for?: string;
            max_difficulty?: number;
            presentation_preferences?: {
                [key: string]: unknown;
            };
        };
        AssistantReply: {
            text: string;
            tone?: string;
            emoji?: string[];
            suggested_next_actions?: string[];
            focus_summary?: string;
        };
        OnboardingState: {
            completed: boolean;
            progress: number;
            missing_topics: string[];
            state: {
                [key: string]: unknown;
            };
        };
        OnboardingChatMessage: {
            /** @enum {string} */
            role: "assistant" | "user";
            content: string;
            /** Format: date-time */
            created_at?: string;
        };
        OnboardingChatRequest: {
            message: string;
            transcript: components["schemas"]["OnboardingChatMessage"][];
            state?: {
                [key: string]: unknown;
            };
        };
        OnboardingChatResponse: {
            assistant_reply: components["schemas"]["AssistantReply"];
            onboarding_state: components["schemas"]["OnboardingState"];
            preference_updates?: {
                [key: string]: unknown;
            };
        };
        GenerateRecipeRequest: {
            prompt: string;
            vibe?: string;
        };
        GenerateRecipeResponse: {
            recipe: components["schemas"]["Recipe"];
            version: components["schemas"]["RecipeVersion"];
            assistant_reply?: components["schemas"]["AssistantReply"];
        };
        TweakRecipeRequest: {
            message: string;
        };
        TweakRecipeResponse: {
            recipe: components["schemas"]["Recipe"];
            version: components["schemas"]["RecipeVersion"];
            assistant_reply?: components["schemas"]["AssistantReply"];
        };
        CreateAttachmentRequest: {
            relation_type: string;
            position?: number;
            prompt?: string;
            recipe?: {
                [key: string]: unknown;
            };
        };
        UpdateAttachmentRequest: {
            relation_type?: string;
            position?: number;
        };
        RecipeDraftMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: date-time */
            created_at?: string;
        };
        RecipeDraft: {
            /** Format: uuid */
            id: string;
            messages: components["schemas"]["RecipeDraftMessage"][];
            active_recipe?: components["schemas"]["Recipe"];
            assistant_reply?: components["schemas"]["AssistantReply"];
            memory_context_ids?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RecipeFinalizeResponse: {
            recipe: components["schemas"]["Recipe"];
            version: components["schemas"]["RecipeVersion"];
            assistant_reply?: components["schemas"]["AssistantReply"];
        };
        Collection: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        GraphEntity: {
            /** Format: uuid */
            id: string;
            entity_type: string;
            label: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        GraphEdge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            from_entity_id: string;
            /** Format: uuid */
            to_entity_id: string;
            relation_type: string;
            confidence: number;
            source?: string;
        };
    };
    responses: {
        /** @description Error envelope */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        RecipeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
