/**
 * Hardcoded admin route inventory — derived from app/api/admin/ route handlers.
 * Kept as a static list because Cloudflare Workers have no filesystem access
 * at runtime. Update this list when adding/removing admin API routes.
 */
export const ADMIN_ROUTES: Array<{ path: string; method: string }> = [
  { path: "/api/admin/changelog", method: "POST" },
  { path: "/api/admin/development/reset/execute", method: "POST" },
  { path: "/api/admin/development/reset/preview", method: "POST" },
  { path: "/api/admin/development/runs", method: "GET" },
  { path: "/api/admin/image/jobs", method: "GET" },
  { path: "/api/admin/image/jobs", method: "POST" },
  { path: "/api/admin/image/jobs/process", method: "POST" },
  { path: "/api/admin/image/jobs/retry", method: "POST" },
  { path: "/api/admin/ingredients/:id", method: "GET" },
  { path: "/api/admin/ingredients/:id", method: "PATCH" },
  { path: "/api/admin/llm/models", method: "GET" },
  { path: "/api/admin/llm/models", method: "POST" },
  { path: "/api/admin/llm/models", method: "PATCH" },
  { path: "/api/admin/llm/models", method: "DELETE" },
  { path: "/api/admin/llm/models/seed", method: "POST" },
  { path: "/api/admin/llm/prompts", method: "GET" },
  { path: "/api/admin/llm/prompts", method: "POST" },
  { path: "/api/admin/llm/routes", method: "GET" },
  { path: "/api/admin/llm/routes", method: "POST" },
  { path: "/api/admin/llm/rules", method: "GET" },
  { path: "/api/admin/llm/rules", method: "POST" },
  { path: "/api/admin/memories", method: "POST" },
  { path: "/api/admin/memories/rebuild", method: "POST" },
  { path: "/api/admin/memories/reset", method: "POST" },
  { path: "/api/admin/memory/jobs", method: "GET" },
  { path: "/api/admin/memory/jobs/:id", method: "GET" },
  { path: "/api/admin/memory/jobs", method: "POST" },
  { path: "/api/admin/memory/jobs/process", method: "POST" },
  { path: "/api/admin/memory/jobs/retry", method: "POST" },
  { path: "/api/admin/metadata/jobs", method: "GET" },
  { path: "/api/admin/metadata/jobs", method: "POST" },
  { path: "/api/admin/metadata/jobs/process", method: "POST" },
  { path: "/api/admin/metadata/jobs/retry", method: "POST" },
  { path: "/api/admin/recipes/:id/canonical", method: "GET" },
  { path: "/api/admin/recipes/:id/causality", method: "GET" },
  { path: "/api/admin/recipes/revert", method: "POST" },
  { path: "/api/admin/request-trace/:requestId", method: "GET" },
  { path: "/api/admin/simulations/run", method: "POST" },
  { path: "/api/admin/users/deactivate", method: "POST" },
  { path: "/api/admin/users/reset-memory", method: "POST" },
  { path: "/api/admin/api-docs", method: "GET" },
];
